admin:
  enabled: true
  super-admin-ids: 5519912522  # –í–∞—à chatId

  # –û–ø—Ü–∏–æ–Ω–∞–ª—å–Ω–æ: –Ω–∞—Å—Ç—Ä–æ–π–∫–∏ —É–≤–µ–¥–æ–º–ª–µ–Ω–∏–π
  notifications:
    verification: true      # –£–≤–µ–¥–æ–º–ª—è—Ç—å –æ –Ω–æ–≤—ã—Ö –∑–∞—è–≤–∫–∞—Ö –Ω–∞ –≤–µ—Ä–∏—Ñ–∏–∫–∞—Ü–∏—é
    support: true          # –£–≤–µ–¥–æ–º–ª—è—Ç—å –æ –Ω–æ–≤—ã—Ö –æ–±—Ä–∞—â–µ–Ω–∏—è—Ö –≤ –ø–æ–¥–¥–µ—Ä–∂–∫—É
    new-users: false       # –£–≤–µ–¥–æ–º–ª—è—Ç—å –æ –Ω–æ–≤—ã—Ö –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è—Ö (–Ω–∞ –±—É–¥—É—â–µ–µ)
    errors: true           # –£–≤–µ–¥–æ–º–ª—è—Ç—å –æ–± –æ—à–∏–±–∫–∞—Ö (–Ω–∞ –±—É–¥—É—â–µ–µ)

server:
  shutdown: graceful  # üî• –í–∫–ª—é—á–∞–µ–º graceful shutdown
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12   # –µ—Å–ª–∏ —Ñ–∞–π–ª –≤ resources, –∏–ª–∏ –∏—Å–ø–æ–ª—å–∑—É–π—Ç–µ –ø–æ–ª–Ω—ã–π –ø—É—Ç—å file:/–ø—É—Ç—å/keystore.p12
    key-store-password: u0740562149       # –ø–∞—Ä–æ–ª—å, –∫–æ—Ç–æ—Ä—ã–π –≤–≤–æ–¥–∏–ª–∏ –ø—Ä–∏ —Å–æ–∑–¥–∞–Ω–∏–∏ keystore
    key-store-type: PKCS12
    key-alias: myalias                    # alias, –∫–æ—Ç–æ—Ä—ã–π –∑–∞–¥–∞–≤–∞–ª–∏ –≤ keytool
# Cloudpub URL
app:
  base-url: https://obdurately-benign-mongoose.cloudpub.ru/

spring:
  application:
    name: tcmatch
  lifecycle:
    timeout-per-shutdown-phase: 30s  # üî• –¢–∞–π–º–∞—É—Ç –¥–ª—è graceful shutdown

  datasource:
    url: jdbc:h2:mem:tcmatchdb
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

jpa:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.tcmatch: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

telegram:
  bot:
    username: ${BOT_USERNAME:TCMatchBot}
    token: ${BOT_TOKEN:000000000}

yoomoney:
  shopId: 1218176
  secretKey: test_BSMXFx9KeUJjYTZdOn2L8yfjAVjTpvW5DCIHIOJYrzI
  returnUrl: https://obdurately-benign-mongoose.cloudpub.ru/payment/success
  notificationUrl: https://obdurately-benign-mongoose.cloudpub.ru/api/v1/payment/notify